### PR TITLE
Update to Squirrel 0.9.0

### PR DESCRIPTION
**Pull request by paulcbetts**
Some [notable points about this release](https://github.com/Squirrel/Squirrel.Windows/compare/0.8.5...0.9.0):

* Fixes orphaned processes hanging around on version obsolete (not sure if Atom hit this)
* Infinite fixes around pinning shortcuts to the Taskbar
* Work around infinite temp files being created which are currently breaking installs for some people
* If the .NET Framework requires a reboot, Setup will now resume itself once the machine restarts
* If users manually right-click on the app and "Run as Administrator", we'll now de-administer ourselves and run Setup, which should fix some permission problems.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Thanks @paulcbetts, published as 0.24.0

**Comment by paulcbetts** [comment]
There's a race that Atom Shell apps _probably_ won't hit, but I'm gonna publish a release for it anyways, will hit you up today

**Comment by kevinsawicki** [comment]
> There's a race that Atom Shell apps probably won't hit

Is there an issue you could link me to about this?

**Comment by paulcbetts** [comment]
https://github.com/Squirrel/Squirrel.Windows/issues/257

**Pull request merged**
