### PR TITLE
add signWithParams argument that gets directly passed to squirrel

### LINKED ISSUE #7: Allow different styles of signing parameters
I'd like to be able to sign with a key already installed on our build machine, which requires a different set of arguments than `certificateFile` and `certificatePassword` arguments can account for.

Any objections to adding a `signWithParams` argument that just gets passed through to squirrel?  Should I deprecate and/or remove `certificateFile` and `certificatePassword` at the same time?

The alternative for me would be adding `keystoreName` and `certificateName` arguments (corresponding to `/s` and `/n` arguments to `signtool.exe`, respectively).

Preferences?

### PR DESCRIPTION
**Pull request by joshuawarner32**
Fixes #7

### CODE REVIEW

**Comment by paulcbetts** [comment]
Into it. Thanks @joshuawarner32!

**Comment by paulcbetts** [comment]
@kevinsawicki Can you push a new release so that the readme docs match up with the package?

**Comment by kevinsawicki** [comment]
Sure thing

**Comment by kevinsawicki** [comment]
0.22 published

**Pull request merged**
